# Generated by Django 4.0.4 on 2022-06-23 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_freepost_freecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='body',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='freecomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snsapp.freepost'),
        ),
    ]
